Aim: Implement Linear Regression Algorithm on the given dataset

In [52]:
import numpy as np
import torch

In [38]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37],
                   [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], 
                   [69,96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96,70]], 
                  dtype='float32')

In [39]:
# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119],
[56, 70], [81, 101], [119, 133], [22, 37], [103, 119],
[56, 70], [81, 101], [119, 133], [22, 37], [103, 119]],
dtype='float32')

In [40]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [41]:
weight = torch.randn(2, 3, requires_grad=True)
bias = torch.randn(2, requires_grad=True)

In [42]:
#define model
def model(inputs):
    return inputs @ weight.t() + bias
#Generate Predictions
preds = model(inputs)
print(preds)

tensor([[-135.8051,  -62.4726],
        [-192.2355,  -79.4374],
        [-206.0748, -102.1930],
        [-114.8997,  -64.2489],
        [-205.1114,  -72.6115],
        [-135.8051,  -62.4726],
        [-192.2355,  -79.4374],
        [-206.0748, -102.1930],
        [-114.8997,  -64.2489],
        [-205.1114,  -72.6115],
        [-135.8051,  -62.4726],
        [-192.2355,  -79.4374],
        [-206.0748, -102.1930],
        [-114.8997,  -64.2489],
        [-205.1114,  -72.6115]], grad_fn=<AddBackward0>)


In [43]:
#mse loss fuction
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

In [44]:
#calculate loss
loss = mse(preds,targets)
print(loss)


tensor(48318.3242, grad_fn=<DivBackward0>)


In [45]:
#compute gradients
loss.backward()
print(weight.grad)
print(bias.grad)

tensor([[-20474.2324, -23184.2129, -14244.4238],
        [-14020.1367, -15803.6865,  -9608.9062]])
tensor([-247.0253, -168.1927])


#Train the model using gradient descent

In [46]:
with torch.no_grad():
    weight -= weight.grad * 1e-5
    bias -= bias.grad * 1e-5
    weight.grad.zero_()
    bias.grad.zero_()

In [47]:
prediction = model(inputs)
loss = mse(prediction, targets)
print(loss)

tensor(32854.8320, grad_fn=<DivBackward0>)


In [48]:
for i in range(100):
    prediction = model(inputs)
    loss = mse(prediction, targets)
    loss.backward()
    with torch.no_grad():
        weight -= weight.grad * 1e-5
        bias -= bias.grad * 1e-5
        weight.grad.zero_()
        bias.grad.zero_()

In [49]:
prediction = model(inputs)
loss = mse(prediction, targets)
print(loss)

tensor(358.7315, grad_fn=<DivBackward0>)


In [51]:
print("predictions: ",prediction)
print("\ntargets: ",targets)

predictions:  tensor([[ 63.9392,  74.0838],
        [ 74.2724, 101.7738],
        [125.8463, 124.3853],
        [ 59.8283,  57.1615],
        [ 65.3768, 109.6354],
        [ 63.9392,  74.0838],
        [ 74.2724, 101.7738],
        [125.8463, 124.3853],
        [ 59.8283,  57.1615],
        [ 65.3768, 109.6354],
        [ 63.9392,  74.0838],
        [ 74.2724, 101.7738],
        [125.8463, 124.3853],
        [ 59.8283,  57.1615],
        [ 65.3768, 109.6354]], grad_fn=<AddBackward0>)

targets:  tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])
