In [ ]:
import numpy as np
import pandas as pd

1) Create a Numpy array of size 4 x 5.

In [ ]:
narray = np.eye(4,5)
print(narray)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


2) Randomly initialize the array.

In [ ]:
narray = np.random.randint(5,size=(4,5))
print(narray)

[[3 3 0 3 2]
 [4 1 3 0 2]
 [1 3 3 4 2]
 [2 3 4 2 1]]


3) Get the Determinant and Transpose of the Matrix that you created.

In [ ]:
print(narray.T) #transpose is 5x4 array

[[3 4 1 2]
 [3 1 3 3]
 [0 3 3 4]
 [3 0 4 2]
 [2 2 2 1]]


4) Create another matrix of size 5 x 4 and randomly initialize it.

In [ ]:
matrix1 = narray
matrix2 = np.random.randint(4,size=(5,4))
print(matrix2)

[[2 1 0 3]
 [1 0 0 3]
 [1 1 3 1]
 [2 1 2 3]
 [1 1 1 3]]


5) Perform Matrix multiplication.

In [ ]:
np.matmul(matrix1,matrix2)

array([[17,  8,  8, 33],
       [14,  9, 11, 24],
       [18, 10, 19, 33],
       [16,  9, 17, 28]])

6) Perform element wise matrix multiplication.

In [ ]:
matrix1 = np.random.randint(5,size=(3,3))
print ("matrix1: \n",matrix1)
matrix2 = np.random.randint(3,size=(3,3))
print ("matrix2: \n",matrix2)
ans = np.multiply(matrix1,matrix2)
print("ans:\n",ans)

matrix1: 
 [[3 3 2]
 [2 1 3]
 [0 0 4]]
matrix2: 
 [[2 0 2]
 [0 0 1]
 [2 1 0]]
ans:
 [[6 0 4]
 [0 0 3]
 [0 0 0]]


7) Find mean, median of the numpy array created.

In [ ]:
print("array is :\n",ans)
print("mean is: ",np.mean(ans))
print("median is: ",np.median(ans))

array is :
 [[6 0 4]
 [0 0 3]
 [0 0 0]]
mean is:  1.4444444444444444
median is:  0.0


8) Obtain each row in the second column of the first array.

In [ ]:
print("array: \n",ans)
print(ans[:,1:2])

array: 
 [[6 0 4]
 [0 0 3]
 [0 0 0]]
[[0]
 [0]
 [0]]


9) Convert Numeric entries(columns) of Iris.csv to Mean Centered Version

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
data = pd.read_csv('drive/MyDrive/Iris.csv')

In [ ]:
d = data.iloc[:,:]
d.mean()

Id               75.500000
SepalLengthCm     5.843333
SepalWidthCm      3.054000
PetalLengthCm     3.758667
PetalWidthCm      1.198667
dtype: float64

10) Study about numpy array attributes and implement it on the first matrix.

In [ ]:
print(narray.shape) #return size of an array
print(narray)


(4, 5)
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [ ]:
narray.shape = (4,5) #we can resize our array
print(narray)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]
